# Generated by Django 4.1.7 on 2023-03-23 16:06

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('razon_social', models.CharField(max_length=100)),
                ('cuit', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('O', 'Ok'), ('B', 'Baja'), ('S', 'Suspendido')], default='O', max_length=1)),
                ('add_date', models.DateTimeField(default=datetime.datetime(2023, 3, 23, 16, 6, 40, 755762, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipodoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.pais', verbose_name='Pais')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('tipo', models.CharField(default='A', max_length=1)),
                ('direccion', models.CharField(default='', max_length=100)),
                ('direccion2', models.CharField(default='', max_length=100)),
                ('cp', models.CharField(default='', max_length=10)),
                ('telefono', models.CharField(default='', max_length=30)),
                ('celular', models.CharField(default='', max_length=30)),
                ('documento', models.CharField(default='', max_length=50)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('N', 'Ingresado'), ('A', 'Aprobado'), ('S', 'Suspendido')], default='N', max_length=1)),
                ('add_date', models.DateTimeField(default=datetime.datetime(2023, 3, 23, 16, 6, 40, 756237, tzinfo=datetime.timezone.utc))),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.ciudad', verbose_name='Ciudad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('genero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.genero', verbose_name='Genero')),
                ('nacionalidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.nacionalidad', verbose_name='Nacionalidad')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.pais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.provincia', verbose_name='Provincia')),
                ('tipodoc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.tipodoc', verbose_name='Tipo documento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.provincia', verbose_name='Provincia'),
        ),
    ]
