# Generated by Django 4.1.7 on 2023-03-23 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='xNacionalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.pais', verbose_name='Pais')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nacionalidad',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 16, 9, 55, 481832, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 16, 9, 55, 482290, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Nacionalidad',
        ),
    ]
