# Generated by Django 4.1.7 on 2023-03-23 16:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0003_nacionalidad_alter_empresa_add_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 23, 16, 11, 14, 443921, tzinfo=datetime.timezone.utc)),
        ),
    ]
