# Generated by Django 4.1.7 on 2023-03-23 16:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0004_alter_empresa_add_date_alter_profile_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
