# Generated by Django 4.1.7 on 2023-03-23 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0005_alter_profile_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.pais'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='provincia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.provincia', verbose_name='Provincia'),
        ),
    ]
