# Generated by Django 4.1.7 on 2023-03-24 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0007_alter_profile_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Com',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('abreviada', models.CharField(max_length=10)),
                ('automatico', models.BooleanField(default=False)),
                ('tipo', models.CharField(choices=[('S', 'Stock'), ('V', 'Facturacion ventas'), ('P', 'Proveedores')], max_length=1)),
                ('signo', models.CharField(choices=[('D', 'Debe'), ('H', 'Haber'), ('T', 'Transferencia')], max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(default='', max_length=30)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ha_totales', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ha_productivas', models.DecimalField(decimal_places=2, max_digits=6)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.campo', verbose_name='Campo')),
            ],
        ),
        migrations.CreateModel(
            name='Mov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_suc', models.IntegerField()),
                ('n_com', models.IntegerField()),
                ('fecha', models.DateField()),
                ('telefono', models.CharField(default='', max_length=30)),
                ('com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.com')),
                ('deposito1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.deposito')),
                ('deposito2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposito2', to='agro.deposito')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='UM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('abreviado', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Trazabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(blank=True, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.actividad')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('id_mov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.mov', verbose_name='Movimiento stock')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.lote')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.profile')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.producto')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.um')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.rubro'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.tipo'),
        ),
        migrations.CreateModel(
            name='Plnificacion_Insumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Insumo', models.CharField(max_length=100)),
                ('Cantidad', models.DecimalField(decimal_places=1, max_digits=4)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desnsidad', models.CharField(choices=[('1', 'Plantas por Hectarea'), ('2', 'Semillas por Hectarea')], default='1', max_length=1)),
                ('profundidad', models.IntegerField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.cultivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrpcion', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Movo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=1, max_digits=4)),
                ('precio_u', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mov', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.mov')),
            ],
        ),
        migrations.AddField(
            model_name='mov',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.producto'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='producto_cultivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cultivo_producto_cultivo', to='agro.producto'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='producto_semilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.producto'),
        ),
        migrations.AddField(
            model_name='com',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.num'),
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini', models.DateField()),
                ('fecha_final', models.DateField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.lote')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.planificacion')),
            ],
        ),
    ]
