# Generated by Django 4.1.7 on 2023-03-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0008_actividad_campo_com_cultivo_deposito_lote_mov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='observaciones',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
