# Generated by Django 4.1.7 on 2023-03-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0009_profile_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='celular',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
