# Generated by Django 4.1.7 on 2023-03-31 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0010_alter_profile_celular_alter_profile_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
