# Generated by Django 4.1.7 on 2023-03-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0011_campo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='campo',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
