# Generated by Django 4.1.7 on 2023-03-31 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0012_campo_image_campo_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='campos'),
        ),
    ]
