# Generated by Django 4.1.7 on 2023-04-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0013_alter_campo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='lotes'),
        ),
    ]
