# Generated by Django 4.1.7 on 2023-04-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0014_lote_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomnbre', models.CharField(max_length=50)),
                ('corto', models.CharField(max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='movo',
            name='cotizacion',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='cotizacion',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=12),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cotizacion', models.DecimalField(decimal_places=3, max_digits=12)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.moneda')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.moneda'),
        ),
        migrations.AddField(
            model_name='movo',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.moneda'),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='moneda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.moneda'),
        ),
    ]
