# Generated by Django 4.1.7 on 2023-04-02 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0015_moneda_movo_cotizacion_trazabilidad_cotizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion_general',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('cotizacion', models.DecimalField(decimal_places=3, max_digits=12)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.moneda')),
            ],
        ),
    ]
