# Generated by Django 4.1.7 on 2023-04-02 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0016_cotizacion_general'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='lotes'),
        ),
        migrations.AddField(
            model_name='producto',
            name='status',
            field=models.CharField(choices=[('O', 'Ok'), ('B', 'Baja')], default='O', max_length=1),
        ),
    ]
