# Generated by Django 4.1.7 on 2023-04-04 17:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0018_rename_nombre_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='agro_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='lotes')),
                ('status', models.CharField(choices=[('O', 'Ok'), ('B', 'Baja')], default='O', max_length=1)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.rubro')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.tipo')),
            ],
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='producto_cultivo',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='producto_semilla',
        ),
        migrations.RemoveField(
            model_name='mov',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='trazabilidad',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
