# Generated by Django 4.1.7 on 2023-04-04 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0019_agro_producto_remove_cultivo_producto_cultivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trazabilidad',
            name='origen_prod',
            field=models.CharField(choices=[('S', 'Sisitema'), ('U', 'Usuario')], default='U', max_length=1),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='producto_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('agro_producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agro.agro_producto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
            bases=('agro.agro_producto',),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='producto_cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivo_producto_cultivo', to='agro.producto'),
        ),
        migrations.AddField(
            model_name='cultivo',
            name='producto_semilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.producto'),
        ),
    ]
