# Generated by Django 4.1.7 on 2023-04-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0020_trazabilidad_origen_prod_trazabilidad_producto_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SistemaCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='empresa',
        ),
        migrations.CreateModel(
            name='agro_CostoProdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotizacion', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('agro_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.agro_producto')),
                ('especificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.especificacion')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.moneda')),
                ('um', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.um')),
            ],
        ),
        migrations.CreateModel(
            name='agro_CostoProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.cultivo')),
                ('sistema_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.sistemacultivo')),
            ],
        ),
        migrations.CreateModel(
            name='CostoProdo',
            fields=[
                ('agro_costoprodo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agro.agro_costoprodo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
            bases=('agro.agro_costoprodo',),
        ),
        migrations.CreateModel(
            name='CostoProd',
            fields=[
                ('agro_costoprod_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='agro.agro_costoprod')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
            bases=('agro.agro_costoprod',),
        ),
        migrations.AddField(
            model_name='agro_costoprodo',
            name='costo_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.costoprod'),
        ),
    ]
