# Generated by Django 4.1.7 on 2023-04-05 00:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0021_especificacion_sistemacultivo_remove_cultivo_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='costoprod',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
