# Generated by Django 4.1.7 on 2023-04-05 15:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0022_costoprod_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costoprod',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
