# Generated by Django 4.1.7 on 2023-04-05 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0023_alter_costoprod_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moneda',
            old_name='nomnbre',
            new_name='nombre',
        ),
    ]
