# Generated by Django 4.1.7 on 2023-04-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0026_agro_tipoprod_agro_producto_agro_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agro_producto',
            name='rubro',
        ),
        migrations.RemoveField(
            model_name='agro_producto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='producto',
            name='rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.rubro'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.tipo'),
        ),
    ]
