# Generated by Django 4.1.7 on 2023-04-06 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0027_remove_agro_producto_rubro_remove_agro_producto_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='agro_RubroProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='agro_producto',
            name='agro_rubro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.agro_rubroprod'),
        ),
    ]
