# Generated by Django 4.1.7 on 2023-04-06 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0028_agro_rubroprod_agro_producto_agro_rubro'),
    ]

    operations = [
        migrations.AddField(
            model_name='agro_producto',
            name='um',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.um'),
        ),
    ]
