# Generated by Django 4.1.7 on 2023-04-06 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0029_agro_producto_um'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especificacion_tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('agro_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.agro_tipoprod')),
            ],
        ),
        migrations.AddField(
            model_name='agro_producto',
            name='especificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.especificacion_tipo'),
        ),
    ]
