# Generated by Django 4.1.7 on 2023-04-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0030_especificacion_tipo_agro_producto_especificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agro_producto',
            name='agro_tipo',
        ),
        migrations.RemoveField(
            model_name='agro_producto',
            name='especificacion',
        ),
        migrations.RemoveField(
            model_name='agro_producto',
            name='um',
        ),
        migrations.AddField(
            model_name='agro_costoprodo',
            name='agro_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.agro_tipoprod'),
        ),
        migrations.AlterField(
            model_name='agro_costoprodo',
            name='especificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.especificacion_tipo'),
        ),
    ]
