# Generated by Django 4.1.7 on 2023-04-06 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0031_remove_agro_producto_agro_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivo',
            name='producto_cultivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cultivo_producto_cultivo', to='agro.agro_producto'),
        ),
        migrations.AlterField(
            model_name='cultivo',
            name='producto_semilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.agro_producto'),
        ),
    ]
