# Generated by Django 4.1.7 on 2023-04-06 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0032_alter_cultivo_producto_cultivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivo',
            name='producto_cultivo',
        ),
        migrations.RemoveField(
            model_name='cultivo',
            name='producto_semilla',
        ),
    ]
