# Generated by Django 4.1.7 on 2023-04-06 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0033_remove_cultivo_producto_cultivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agro_costoprodo',
            name='costo_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.agro_costoprod'),
        ),
    ]
