# Generated by Django 4.1.7 on 2023-04-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0034_alter_agro_costoprodo_costo_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agro_costoprodo',
            name='cantidad',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
