# Generated by Django 4.1.7 on 2023-04-07 19:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0035_alter_agro_costoprodo_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='xCostoProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.cultivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('sistema_cultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.sistemacultivo')),
            ],
        ),
        migrations.CreateModel(
            name='xCostoProdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cotizacion', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('agro_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.agro_producto')),
                ('agro_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.agro_tipoprod')),
                ('costo_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.agro_costoprod')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('especificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.especificacion_tipo')),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.moneda')),
                ('um', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.um')),
            ],
        ),
        migrations.RemoveField(
            model_name='costoprodo',
            name='agro_costoprodo_ptr',
        ),
        migrations.RemoveField(
            model_name='costoprodo',
            name='empresa',
        ),
        migrations.AlterModelOptions(
            name='agro_costoprodo',
            options={'ordering': ['costo_prod', 'orden']},
        ),
        migrations.DeleteModel(
            name='CostoProd',
        ),
        migrations.DeleteModel(
            name='CostoProdo',
        ),
    ]
