# Generated by Django 4.1.7 on 2023-04-07 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0037_costoprod_costoprodo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costoprodo',
            name='agro_producto',
        ),
        migrations.AddField(
            model_name='costoprodo',
            name='origen',
            field=models.CharField(choices=[('A', 'Agro'), ('U', 'Usuario')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='costoprodo',
            name='producto_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costoprodo',
            name='costo_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.costoprod'),
        ),
    ]
