# Generated by Django 4.1.7 on 2023-04-07 20:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0038_remove_costoprodo_agro_producto_costoprodo_origen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='xProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='lotes')),
                ('status', models.CharField(choices=[('O', 'Ok'), ('B', 'Baja')], default='O', max_length=1)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('agro_rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.agro_rubroprod')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('rubro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.rubro')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.tipo')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
