# Generated by Django 4.1.7 on 2023-04-10 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0040_producto_delete_xproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='agro_producto',
            name='agro_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.agro_tipoprod'),
        ),
        migrations.AddField(
            model_name='producto',
            name='agro_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.agro_tipoprod'),
        ),
    ]
