# Generated by Django 4.1.7 on 2023-04-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0041_agro_producto_agro_tipo_producto_agro_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agro_costoprodo',
            name='agro_tipo',
        ),
        migrations.RemoveField(
            model_name='costoprodo',
            name='agro_tipo',
        ),
    ]
