# Generated by Django 4.1.7 on 2023-04-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0042_remove_agro_costoprodo_agro_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agro_rubroprod',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
