# Generated by Django 4.1.7 on 2023-04-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0043_agro_rubroprod_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='agro_rubroprod',
            name='letra',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
