# Generated by Django 4.1.7 on 2023-04-15 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0044_agro_rubroprod_letra'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agro_producto',
            options={'ordering': ['descripcion']},
        ),
    ]
