# Generated by Django 4.1.7 on 2023-04-18 19:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0045_agro_etapa_alter_agro_producto_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planificacion',
            old_name='desnsidad',
            new_name='densidad',
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='cultivo',
        ),
        migrations.AddField(
            model_name='planificacion',
            name='costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.costoprod'),
        ),
        migrations.AddField(
            model_name='planificacion',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
