# Generated by Django 4.1.7 on 2023-04-20 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0045_alter_agro_producto_options'),
        ('agro', '0048_agro_cotizacioncultivo'),
    ]

    operations = [
    ]
