# Generated by Django 4.1.7 on 2023-04-21 21:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0049_merge_20230420_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_desde', models.DateField(default=django.utils.timezone.now)),
                ('fecha_hasta', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion_cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_plani', models.DateField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('fecha_desde', models.DateField(default=django.utils.timezone.now)),
                ('fecha_hasta', models.DateField(default=django.utils.timezone.now)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.campana')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Planificacion_lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.costoprod')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.lote')),
                ('planificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.planificacion_cultivo')),
            ],
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='planificacion',
            name='empresa',
        ),
        migrations.AddField(
            model_name='planificacion_etapas',
            name='lote',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='agro.lote'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agro_tipoprod',
            name='etapas',
            field=models.ManyToManyField(blank=True, to='agro.agro_etapa'),
        ),
        migrations.DeleteModel(
            name='Calendario',
        ),
        migrations.AlterField(
            model_name='planificacion_etapas',
            name='planificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.planificacion_cultivo'),
        ),
        migrations.DeleteModel(
            name='Planificacion',
        ),
    ]
