# Generated by Django 4.1.7 on 2023-04-21 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0050_campana_planificacion_cultivo_planificacion_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='empresa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='agro.empresa'),
            preserve_default=False,
        ),
    ]
