# Generated by Django 4.1.7 on 2023-04-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0051_campana_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campana',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
