# Generated by Django 4.1.7 on 2023-04-27 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0052_alter_campana_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion_lote',
            name='costo',
        ),
        migrations.AddField(
            model_name='planificacion_cultivo',
            name='costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.costoprod'),
        ),
    ]
