# Generated by Django 4.1.7 on 2023-05-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0053_remove_planificacion_lote_costo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion_etapas',
            name='agro_producto',
        ),
        migrations.AddField(
            model_name='planificacion_etapas',
            name='origen',
            field=models.CharField(choices=[('A', 'Agro'), ('U', 'Usuario')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='planificacion_etapas',
            name='producto_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
