# Generated by Django 4.1.7 on 2023-05-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0053_remove_planificacion_lote_costo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
    ]
