# Generated by Django 4.1.7 on 2023-05-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0054_comprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobantes',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=10)),
                ('image', models.ImageField(default='default.jpg', upload_to='comprobante')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.DeleteModel(
            name='Comprobante',
        ),
    ]
