# Generated by Django 4.1.7 on 2023-05-01 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0054_remove_planificacion_etapas_agro_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apli_costo_etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plani_costoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.costoprodo')),
                ('plani_etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.planificacion_etapas')),
            ],
        ),
    ]
