# Generated by Django 4.1.7 on 2023-05-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0055_apli_costo_etapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='apli_costo_etapa',
            name='cant_aplicada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
