# Generated by Django 4.1.7 on 2023-05-03 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0055_comprobantes_delete_comprobante'),
        ('agro', '0056_apli_costo_etapa_cant_aplicada'),
    ]

    operations = [
    ]
