# Generated by Django 4.1.7 on 2023-05-05 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0057_merge_20230504_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planificacion_etapas',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='planificacion_etapas',
            name='cotizacion',
        ),
        migrations.RemoveField(
            model_name='planificacion_etapas',
            name='especificacion',
        ),
        migrations.RemoveField(
            model_name='planificacion_etapas',
            name='lote',
        ),
        migrations.RemoveField(
            model_name='planificacion_etapas',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='planificacion_etapas',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='planificacion_etapas',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='planificacion_etapas',
            name='producto_id',
        ),
        migrations.RemoveField(
            model_name='planificacion_etapas',
            name='um',
        ),
        migrations.AddField(
            model_name='planificacion_etapas',
            name='cant_aplicada',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planificacion_etapas',
            name='costoo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.costoprodo'),
        ),
        migrations.DeleteModel(
            name='Apli_costo_etapa',
        ),
    ]
