# Generated by Django 4.1.7 on 2023-05-03 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0057_merge_20230503_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comprobantes',
        ),
    ]
