# Generated by Django 4.1.7 on 2023-05-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0058_delete_comprobantes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apli_costo_etapa',
            name='cant_aplicada',
        ),
    ]
