# Generated by Django 4.1.7 on 2023-05-15 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0058_delete_comprobantes'),
        ('agro', '0058_remove_planificacion_etapas_cantidad_and_more'),
    ]

    operations = [
    ]
