# Generated by Django 4.1.7 on 2023-05-17 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0059_merge_20230515_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mov',
            name='telefono',
        ),
        migrations.AddField(
            model_name='mov',
            name='observaciones',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='movo',
            name='origen',
            field=models.CharField(choices=[('A', 'Agro'), ('U', 'Usuario')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='movo',
            name='producto_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='especificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.especificacion_tipo'),
        ),
        migrations.AddField(
            model_name='trazabilidad',
            name='planificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.planificacion_cultivo'),
        ),
        migrations.AlterField(
            model_name='mov',
            name='deposito2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deposito2', to='agro.deposito'),
        ),
        migrations.AlterField(
            model_name='movo',
            name='cotizacion',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='movo',
            name='precio_u',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
