# Generated by Django 4.1.7 on 2023-05-10 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0058_remove_planificacion_etapas_cantidad_and_more'),
        ('agro', '0059_remove_apli_costo_etapa_cant_aplicada'),
    ]

    operations = [
    ]
