# Generated by Django 4.1.7 on 2023-06-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0060_remove_mov_telefono_mov_observaciones_movo_origen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agro_tipoprod',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
