# Generated by Django 4.1.7 on 2023-06-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0061_agro_tipoprod_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='agro_rubroprod',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
