# Generated by Django 4.1.7 on 2023-06-08 23:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0062_agro_rubroprod_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroLluvia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('cantidad', models.IntegerField(default=0)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.campo', verbose_name='Campo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
    ]
