# Generated by Django 4.1.7 on 2023-06-12 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0063_registrolluvia'),
    ]

    operations = [
        migrations.CreateModel(
            name='agro_CategoriaContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='agro_Ivapos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.com')),
            ],
        ),
        migrations.CreateModel(
            name='Contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=60)),
                ('categorias', models.ManyToManyField(blank=True, to='agro.agro_categoriacontacto')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(max_length=20)),
                ('razon_social', models.CharField(max_length=50)),
                ('nombre_fantasia', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=250)),
                ('cuit', models.CharField(max_length=30)),
                ('contactos', models.ManyToManyField(blank=True, to='agro.contactos')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('ivapos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.agro_ivapos')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['razon_social'],
            },
        ),
    ]
