# Generated by Django 4.1.7 on 2023-06-13 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0064_agro_categoriacontacto_agro_ivapos_contactos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedores',
            new_name='Proveedor',
        ),
    ]
