# Generated by Django 4.1.7 on 2023-06-23 22:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0066_alter_registrolluvia_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrolluvia',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
