# Generated by Django 4.1.7 on 2023-07-14 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0067_alter_registrolluvia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='codigo',
            field=models.CharField(default='  ', max_length=2),
            preserve_default=False,
        ),
    ]
