# Generated by Django 4.1.7 on 2023-07-14 16:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0068_actividad_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(default=django.utils.timezone.now)),
                ('fecha_hasta', models.DateField(default=django.utils.timezone.now)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.cultivo')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.lote')),
                ('planificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.planificacion_cultivo')),
            ],
        ),
    ]
