# Generated by Django 4.1.7 on 2023-08-09 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0069_estadolote'),
    ]

    operations = [
        migrations.AddField(
            model_name='trazabilidad',
            name='estado_lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.estadolote'),
        ),
    ]
