# Generated by Django 4.1.7 on 2023-08-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0070_trazabilidad_estado_lote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trazabilidad',
            name='lote',
        ),
    ]
