# Generated by Django 4.1.7 on 2023-08-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0071_remove_trazabilidad_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadolote',
            name='estado',
            field=models.CharField(choices=[('A', 'Abierto'), ('C', 'Cerrado')], default='A', max_length=1),
        ),
    ]
