# Generated by Django 4.1.7 on 2023-08-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0072_estadolote_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='agro_tipo',
            field=models.ManyToManyField(to='agro.agro_tipoprod'),
        ),
    ]
