# Generated by Django 4.1.7 on 2023-08-14 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0073_actividad_agro_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trazabilidad',
            name='planificacion',
        ),
    ]
