# Generated by Django 4.2.4 on 2023-09-11 19:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0075_agro_producto_um_producto_um'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(choices=[('I', 'Insumo'), ('P', 'Producto venta')], max_length=1)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('observaciones', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='lotes')),
                ('status', models.CharField(choices=[('O', 'Ok'), ('B', 'Baja')], default='O', max_length=1)),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.claseprod')),
            ],
        ),
        migrations.CreateModel(
            name='RubroProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Prod_Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.prod')),
            ],
        ),
        migrations.AddField(
            model_name='prod',
            name='rubro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.rubroprod'),
        ),
        migrations.AddField(
            model_name='prod',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.tipoprod'),
        ),
        migrations.AddField(
            model_name='prod',
            name='um',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.um'),
        ),
    ]
