# Generated by Django 4.2.4 on 2023-09-11 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0076_claseprod_prod_rubroprod_tipoprod_prod_conf_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prod_Conf',
        ),
    ]
