# Generated by Django 4.2.4 on 2023-09-11 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0077_delete_prod_conf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='rubro',
        ),
        migrations.CreateModel(
            name='Prod_Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.prod')),
                ('rubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.rubroprod')),
            ],
        ),
    ]
