# Generated by Django 4.2.4 on 2023-09-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0078_remove_prod_rubro_prod_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_conf',
            name='descripcion',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
