# Generated by Django 4.2.4 on 2023-09-11 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0081_rename_especifiacion_prod_especificacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rubroprod',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agro.empresa'),
            preserve_default=False,
        ),
    ]
