# Generated by Django 4.2.4 on 2023-09-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0083_alter_prod_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_conf',
            name='descripcion',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='prod_conf',
            name='especificacion',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
