# Generated by Django 4.2.4 on 2023-09-14 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0084_alter_prod_conf_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='moneda',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agro.moneda'),
            preserve_default=False,
        ),
    ]
