# Generated by Django 4.2.4 on 2023-09-14 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0085_alter_empresa_moneda'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrazaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.empresa')),
                ('estado_lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.estadolote')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TrazaLoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('o', models.IntegerField()),
                ('especificacion', models.CharField(default='', max_length=80)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cotizacion', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.moneda')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.prod')),
                ('trazalote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.trazalote')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agro.um')),
            ],
        ),
    ]
