# Generated by Django 4.2.4 on 2023-09-14 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0086_trazalote_trazaloteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='trazalote',
            name='actividad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agro.actividad'),
            preserve_default=False,
        ),
    ]
