# Generated by Django 4.2.4 on 2023-09-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0087_trazalote_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod',
            name='especificacion',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
