# Generated by Django 4.2.4 on 2023-09-15 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0088_alter_prod_especificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_conf',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agro.tipoprod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prod_conf',
            name='um',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agro.um'),
            preserve_default=False,
        ),
    ]
