# Generated by Django 4.2.4 on 2023-09-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0089_prod_conf_tipo_prod_conf_um'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_conf',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.tipoprod'),
        ),
        migrations.AlterField(
            model_name='prod_conf',
            name='um',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agro.um'),
        ),
    ]
