# Generated by Django 4.2.4 on 2023-09-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0090_alter_prod_conf_tipo_alter_prod_conf_um'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod_conf',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='lotes'),
        ),
    ]
