# Generated by Django 4.2.4 on 2023-09-15 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0091_prod_conf_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prod_conf',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='lotes'),
        ),
    ]
