# Generated by Django 4.2.16 on 2025-04-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0092_alter_prod_conf_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=10)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='campo',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
