# Generated by Django 4.2.21 on 2025-05-14 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0094_archivodato_datogeo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='lotes/')),
                ('extension', models.CharField(max_length=20)),
                ('tipo', models.CharField(choices=[('cosecha', 'Cosecha'), ('suelo', 'Análisis de Suelo')], max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='agro.lote')),
            ],
        ),
    ]
