# Generated by Django 4.2.21 on 2025-05-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0095_archivolote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivolote',
            name='tipo',
            field=models.CharField(choices=[('cosecha', 'Colheita'), ('n', 'Nitrogênio'), ('p', 'Fósforo'), ('k', 'Potássio'), ('s', 'Enxofre'), ('ph', 'pH'), ('compactacion', 'Compactação'), ('ca', 'Cálcio'), ('mg', 'Magnésio'), ('mo', 'Matéria Orgânica'), ('ctc', 'CTC'), ('sat_base', 'Saturação de Bases'), ('al', 'Alumínio'), ('m', 'Micronutrientes'), ('zn', 'Zinco'), ('b', 'Boro'), ('cu', 'Cobre'), ('mn', 'Manganês'), ('fe', 'Ferro')], max_length=20, verbose_name='Tipo de dado'),
        ),
    ]
